FROM node:latest

WORKDIR /usr/src/app

COPY package.json ./ 

# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
